# Copyright (c) 2017 David Pfander
# Copyright (c) 2017-2018 Patrick Diehl
# Copyright (c) 2017-2019 Dominic Marcello
# Copyright (c) 2019 Parsa Amini
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

version: 2

anchors:
    - &docker_config
        docker:
            - image: stellargroup/octotiger:prerequisites-gcc6

jobs:
    build:
        <<: *docker_config
        steps:
            - checkout:
                path: /octotiger
            - run:
                name: Configure Octotiger
                command: |
                    cmake -H/octotiger -B/octotiger/build \
                          -DCMAKE_BUILD_TYPE=Release \
                          -DHPX_DIR=/local/hpx/lib/cmake/HPX \
                          -DVc_DIR=/local/vc/lib/cmake/Vc \
                          -DSilo_DIR=/local/silo \
                          -DHDF5_ROOT=/local/hdf5 \
                          -DBOOST_ROOT=/local/boost \
                          -GNinja
            - run:
                name: Build
                command: cmake --build /octotiger/build -- -j2
            - persist_to_workspace:
                root: /
                paths:
                    - octotiger/build

    test_marshak:
        <<: *docker_config
        working_directory: /test
        steps:
            - checkout:
                path: /octotiger
            - attach_workspace:
                at: /
            - restore_cache:
                keys:
                    - test_marshak-v2
            - run:
                name: Download integrity check reference
                command: wget -nc phys.lsu.edu/~dmarcel/marshak.2.silo
            - save_cache:
                key: test_marshak-v2
                paths:
                    /test
            - run:
                name: Marshak wave test
                command: /octotiger/build/octotiger --config_file=/octotiger/test_problems/marshak/marshak.ini
            - run:
                name: Check Integrity
                command: |
                    silodiff -q -x 1.0 -R 1.0e-12 marshak.2.silo final.silo >diff.txt
                    ! grep ".vals" diff.txt | tee vals.txt
            - store_artifacts:
                path: /test

    test_blast:
        <<: *docker_config
        working_directory: /test
        steps:
            - checkout:
                path: /octotiger
            - attach_workspace:
                at: /
            - restore_cache:
                keys:
                    - test_blast-v4
            - run:
                name: Download integrity check reference
                command: wget -nc phys.lsu.edu/~dmarcel/blast.4.silo
            - save_cache:
                key: test_blast-v4
                paths:
                    /test
            - run:
                name: Blast test
                command: /octotiger/build/octotiger --config_file=/octotiger/test_problems/blast/blast.ini
            - run:
                name: Check Integrity
                command: |
                    silodiff -q -x 1.0 -R 1.0e-12 blast.4.silo final.silo >diff.txt
                    ! grep ".vals" diff.txt | tee vals.txt
            - store_artifacts:
                path: /test

    test_sod:
        <<: *docker_config
        working_directory: /test
        steps:
            - checkout:
                path: /octotiger
            - attach_workspace:
                at: /
            - restore_cache:
                keys:
                    - test_sod-v4
            - run:
                name: Download integrity check reference
                command: wget -nc phys.lsu.edu/~dmarcel/sod.4.silo
            - save_cache:
                key: test_sod-v4
                paths:
                    /test
            - run:
                name: Sod shock tube test
                command: /octotiger/build/octotiger --config_file=/octotiger/test_problems/sod/sod.ini
            - run:
                name: Check Integrity
                command: |
                    silodiff -q -x 1.0 -R 1.0e-12 sod.4.silo final.silo >diff.txt
                    ! grep ".vals" diff.txt | tee vals.txt
            - store_artifacts:
                path: /test

    test_sphere:
        <<: *docker_config
        working_directory: /test
        steps:
            - checkout:
                path: /octotiger
            - attach_workspace:
                at: /
            - restore_cache:
                keys:
                    - test_sphere-v1
            - run:
                name: Download integrity check reference
                command: wget -nc phys.lsu.edu/~dmarcel/sphere.2.silo
            - save_cache:
                key: test_sphere-v1
                paths:
                    /test
            - run:
                name: Solid sphere test
                command: /octotiger/build/octotiger --config_file=/octotiger/test_problems/sphere/sphere.ini
            - run:
                name: Check Integrity
                command: |
                    silodiff -q -x 1.0 -R 1.0e-12 sphere.2.silo X.silo >diff.txt
                    ! grep ".vals" diff.txt | tee vals.txt
            - store_artifacts:
                path: /test

    test_rotating_star:
        <<: *docker_config
        working_directory: /test
        steps:
            - checkout:
                path: /octotiger
            - attach_workspace:
                at: /
            - restore_cache:
                keys:
                    - test_rotating_star-v1
            - run:
                name: Download integrity check reference
                command: wget -nc phys.lsu.edu/~dmarcel/rotating_star.2.silo
            - save_cache:
                key: test_rotating_star-v1
                paths:
                    /test
            - run:
                name: Generate Init
                command: /octotiger/build/gen_rotating_star_init
            - run:
                name: Rotating star test
                command: /octotiger/build/octotiger --config_file=/octotiger/test_problems/rotating_star/rotating_star.ini 
            - run:
                name: Check Integrity
                command: |
                    silodiff -q -x 1.0 -R 1.0e-12 rotating_star.2.silo final.silo >diff.txt
                    ! grep ".vals" diff.txt | tee vals.txt
            - store_artifacts:
                path: /test

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test_marshak:
                requires:
                    - build
            - test_blast:
                requires:
                    - build
            - test_sod:
                requires:
                    - build
            - test_rotating_star:
                requires:
                    - build
            - test_sphere:
                requires:
                    - build
